apiVersion: v1
kind: Service
metadata:
  name: blockchain-service
spec:
  selector:
    app: blockchain
  ports:
    - name: p2p
      port: 5000
      targetPort: 5000
    - name: api
      port: 5001
      targetPort: 5001
  clusterIP: None  # 使用Headless Service